### ISSUE TITLE
看起来不错

### ISSUE THREAD

**Issue by xgugugu** [WP-Studio01/NewBlog#1]
看到了你这个新项目，用的React框架搞动态页面，比我用jQuery手搓的效率高的不是一点半点哎

不过为什么不用markdown写文章呢（markdown比html简单了不止一点半点，而且还兼容html的语法）

**Comment by WP-Studio01** [comment]
呵呵，你真是个大聪明，HTML能解析Markdown，佩服佩服



在 2022-12-19 17:33:14，"咕咕" ***@***.***> 写道：

看到了你这个新项目，用的React框架搞动态页面，比我用jQuery手搓的效率高的不是一点半点哎

不过为什么不用markdown写页面呢（markdown比html简单了不止一点半点，而且还兼容html的语法）

**Comment by xgugugu** [comment]
> 呵呵，你真是个大聪明，HTML能解析Markdown，佩服佩服 在 2022-12-19 17:33:14，"咕咕" ***@***.***> 写道： 看到了你这个新项目，用的React框架搞动态页面，比我用jQuery手搓的效率高的不是一点半点哎 不过为什么不用markdown写页面呢（markdown比html简单了不止一点半点，而且还兼容html的语法） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

本来就可以，不信你自己去翻我网页的代码

加个marked.js不就行了

**Comment by WP-Studio01** [comment]
知道了



在 2022-12-19 18:53:17，"咕咕" ***@***.***> 写道：

呵呵，你真是个大聪明，HTML能解析Markdown，佩服佩服 在 2022-12-19 17:33:14，"咕咕" @.> 写道： 看到了你这个新项目，用的React框架搞动态页面，比我用jQuery手搓的效率高的不是一点半点哎 不过为什么不用markdown写页面呢（markdown比html简单了不止一点半点，而且还兼容html的语法） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>

本来就可以，不信你自己去翻我网页的代码

加个marked.js不就行了

**Comment by WP-Studio01** [comment]
对不起，冒犯了，是的是的



在 2022-12-19 18:53:17，"咕咕" ***@***.***> 写道：

呵呵，你真是个大聪明，HTML能解析Markdown，佩服佩服 在 2022-12-19 17:33:14，"咕咕" @.> 写道： 看到了你这个新项目，用的React框架搞动态页面，比我用jQuery手搓的效率高的不是一点半点哎 不过为什么不用markdown写页面呢（markdown比html简单了不止一点半点，而且还兼容html的语法） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>

本来就可以，不信你自己去翻我网页的代码

加个marked.js不就行了
